version: '3.8'
services:
  mongodb:
    container_name: 'ququiz-mongo'
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    env_file:
      - ./.env
  dkron:
    image: dkron/dkron
    ports:
      - '9911:8080'
    command: agent --server --bootstrap-expect=1 --node-name=node1
    environment:
      - DKRON_BACKEND_MACHINE_URL=dkron://dkron:8946
    restart: always
  rabbitmq:
    image: rabbitmq:3.13.1-management
    container_name: ququiz-rabbitmq
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 500mb
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  quiz:
    container_name: "ququiz-quiz"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3502:3000
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
    depends_on:
      - mongodb
